### ISSUE TITLE
Add tutorial 010

### ISSUE THREAD

**Issue by akranga** [epam/hubctl.io#1]
Add documentation for first tutorial. Scenario
- [x] User initializes a project form URL
- [x] Add component reference to hub.yaml
- [x]  Project has one component with `echo hello foo` shell script (or similar message) where `foo` has been parametrised
- [x] User changes parameter on a stack level to `bar` and deploys 
- [x] User adds another instance of the same component 
- [x] User adds parameter sourced `fromEnv` with default `baz`
- [x] User deploys second component
- [x] Description to README.md (details about scenario steps)

**Comment by akranga** [comment]
Related commit a2877f64ef0e3b55f1b52bc3ee8147ea3a9c508b

**Comment by NellyHargeliya** [comment]
Added changing for 010 and 015 tutorials https://github.com/epam/hubctl.io/pull/6
