### ISSUE TITLE
Tutorial for s3 and aws

### ISSUE THREAD

**Issue by akranga** [epam/hubctl.io#10]
# Create S3 Bucket component

We need to create as simple as possible tutorial for Terraform. This tutorial should lead user further. They will need to create a stack that requires `aws` and a component that requires to have `aws` and `component`

This component should produce a `bucket` that exposes well known parameters (TODO need link to the doc with common parameters for buckets)

- [x] Create s3bucket component that uses Terraform based on https://registry.terraform.io/modules/terraform-aws-modules/s3-bucket/aws/latest 
- [x] Component should have a private ACL by default passed to the component as a `TF_VAR_*` variable
- [x] Component should have a bucket name that defaults to `hub.stackName` parameter which defaults to `HUB_STACK_NAME` environment variable on a stack level. This variable will trigger auto-generated name for bucket
- [x] Bucket should output parameters similar to `gsbucket` component with exception of access and secret key
- [x] Create tutorial that guides user through this and explains meaning of `HUB_STACK_NAME` parameter (need link to the doc)
- [x] Tutorial should explain though the `aws/configure` steps why this is important 
- [x] Create a separate documentation article about common parameters for buckets
- [x] Capture terraform outputs `fromTfVar`

Bucket input parameters

- `bucket.region`
- `bucket.name`

Output parametrers 

- `bucket.endpoint`

**Comment by akranga** [comment]
@NellyHargeliya @seseque would you care to handle this request?

**Comment by NellyHargeliya** [comment]
- Created https://github.com/epam/hub-extensions/pull/85 for adding the condition of the hosted zone ID from the Route 53
- Created https://github.com/epam/hubctl.io/pull/14 for the tutorial
